In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [40]:
np.arange(2, 7)

array([2, 3, 4, 5, 6])

In [10]:
np.linspace(0, 10, 3) # creates array with evenly spaced elements in a given range

array([ 0.,  5., 10.])

# Multi-dimensional array

In [17]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

n[2] = [0, 0, 0] # to change the rows
n

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [22]:
n[:, 2] = [9, 9, 9] # to change the column
n

array([[1, 2, 9],
       [4, 5, 9],
       [0, 0, 9]])

# Randomly generated array

In [27]:
np.random.seed(3) # same random numbers when run again
np.random.rand(5, 3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ]])

# Element-wise operations

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [32]:
a > 2

array([False, False, False,  True,  True])

In [33]:
a > b

array([False, False, False, False, False])

# Summarize

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:

a.std() # S.D

1.4142135623730951

In [37]:
a.min()


4

In [38]:
a.max()

4

In [39]:
a.sum()

10